- name: this is our first play.
# we can add group as well as single server of any group
  hosts: webservers 
  remote_user: ubuntu    
  # become: yes                    
  tasks:
    - name: "create a dummy file on websever1"
      command: touch /tmp/ansible_dummy.txt
- name: Update sql servers
  hosts: databaseservers
  remote_user: ubuntu
  # become: yes
  tasks:
    - name: Ensure nginx is at the latest version
      apt:
        name: nginx
        state: present